permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: 松林
  email: ux_lsl@163.com
  link: http://uxlsl.org
  weibo: http://weibo.com/yansu0711
  github: http://github.com/uxlsl

# 站点信息
title: 松林的博客
description: 松林的博客
url: http://uxlsl.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar:  http://7xnnj6.com1.z0.glb.clouddn.com/sandy.jpg
favicon: http://7xnnj6.com1.z0.glb.clouddn.com/thumb-sandy.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: uxlsl

# links
links:
  Peter: http://www.godblessyuan.com
